export const DEFAULT_THEME_ID = "blue-white";

export const THEMES = [
  {
    id: "blue-white",
    label: "Blue & White",
    mode: "light",
    accent: "#2563eb",
    accentHover: "#1d4ed8",
    accentSoft: "#dbeafe",
    onAccent: "#ffffff",
    bg: "#f8fafc",
    surface: "#ffffff",
    text: "#0f172a",
    textMuted: "#64748b",
    border: "#e2e8f0",
  },
  {
    id: "blue-black",
    label: "Blue & Black",
    mode: "dark",
    accent: "#3b82f6",
    accentHover: "#60a5fa",
    accentSoft: "#1e3a5f",
    onAccent: "#081020",
    bg: "#0b0f19",
    surface: "#131826",
    text: "#f1f5f9",
    textMuted: "#94a3b8",
    border: "#232a3b",
  },
  {
    id: "pink-white",
    label: "Pink & White",
    mode: "light",
    accent: "#db2777",
    accentHover: "#be185d",
    accentSoft: "#fce7f3",
    onAccent: "#ffffff",
    bg: "#fdf2f8",
    surface: "#ffffff",
    text: "#27101d",
    textMuted: "#9d6b85",
    border: "#f3d0e3",
  },
  {
    id: "pink-black",
    label: "Pink & Black",
    mode: "dark",
    accent: "#f472b6",
    accentHover: "#f9a8d4",
    accentSoft: "#3f1230",
    onAccent: "#1a0a13",
    bg: "#120a10",
    surface: "#1c1218",
    text: "#fdf2f8",
    textMuted: "#c9a3b5",
    border: "#33202a",
  },
  {
    id: "emerald-white",
    label: "Emerald & White",
    mode: "light",
    accent: "#059669",
    accentHover: "#047857",
    accentSoft: "#d1fae5",
    onAccent: "#ffffff",
    bg: "#f0fdf9",
    surface: "#ffffff",
    text: "#0f172a",
    textMuted: "#64748b",
    border: "#d1e7dd",
  },
  {
    id: "violet-white",
    label: "Violet & White",
    mode: "light",
    accent: "#7c3aed",
    accentHover: "#6d28d9",
    accentSoft: "#ede9fe",
    onAccent: "#ffffff",
    bg: "#f5f3ff",
    surface: "#ffffff",
    text: "#1e1b2e",
    textMuted: "#6b6478",
    border: "#e5e0fa",
  },
];

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES.find((t) => t.id === DEFAULT_THEME_ID);
}
